subjects = [
    "You",
    "The shadow",
    "The moon",
    "The maiden",
    "The stone",
    "The spire",
    "The dragon",
    "The night",
    "The dawn",
    "The garden",
    "The storm",
    "The phoenix",
    "The elder",
    "The flame",
    "The wolf",
    "The ancient tree",
    "The star",
    "The oracle",
    "The king",
    "The wanderer",
    "The sword",
    "The sea",
    "The mountain",
    "The raven",
    "The forgotten city",
    "The eternal fire",
    "The mystic river",
    "The hero",
    "The wind",
    "The serpent",
    "The light",
    "The duke",
]

actions = [
    "will find",
    "shall bring",
    "will overcome",
    "shall linger",
    "will cry",
    "shall rejoice",
    "will prepare",
    "shall bring fortune",
    "will give luck",
    "will become conspicuous",
    "shall awaken",
    "will descend upon",
    "shall whisper",
    "will rise",
    "shall protect",
    "will conquer",
    "will be consumed by",
    "shall be born from",
    "shall discover",
    "will challenge",
    "shall unleash",
    "will shatter",
    "shall unite",
    "shall ignite",
    "will surrender to",
    "shall call upon"
]

objects = [
    "great destiny",
    "good luck",
    "a surprise",
    "the shadow",
    "the stone arch",
    "the radiant sun",
    "fortune and destiny",
    "the forest of dreams",
    "the shadow of the spire",
    "beneath the moon",
    "ancient wisdom",
    "a hidden power",
    "eternal light",
    "the cursed flame",
    "the lost crown",
    "the forgotten king",
    "the elder scroll",
    "the secret path",
    "the dragon’s heart",
    "the eternal frost",
    "the fallen star",
    "the golden key",
    "the final hour",
    "the storm’s wrath",
    "the sea of souls",
    "the shattered realm",
    "the sword of truth",
    "the endless storm",
    "the heart of the mountain",
    "the veil of shadows"
]

spatial_prepositions = [
    "in",
    "beneath",
    "under",
    "within",
    "above",
    "beside",
    "at the edge of",
    "beyond",
    "before",
    "through",
    "across",
    "upon the peak of",
    "in the depths of",
    "alongside",
    "in the heart of",
    "amidst",
    "underneath",
    "near",
    "within the grasp of"
]

temporal_prepositions = [
    "at",
    "on",
    "during",
    "before",
    "after",
    "until",
    "since"
]

places = [
    "the full moon",
    "the forest",
    "the garden",
    "the shadow",
    "the arch",
    "the blood moon",
    "the final battle",
    "the storm’s eye",
    "the bridge",
    "the starry sky",
    "the eternal flame",
    "the darkened path",
    "the tavern",
    "the distant horizon",
    "the waning moon",
    "the rising sun",
    "the tower",
    "the valley",
    "the river"
]

times = [
    "the morning",
    "the dawn",
    "the night",
    "noon",
    "tomorrow",
    "the full moon",
    "the evening",
    "the next eclipse",
    "the ancient hour",
    "the final battle",
    "the solstice",
    "the twilight",
    "the golden hour",
    "the waning moon",
    "the rising sun",
    "the midnight hour"
]
